cache: pip
dist: xenial

matrix:
  include:
    - language: python

      virtualenv:
        system_site_packages: true

      python: "3.5"

      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install --no-install-recommends
        - sudo apt-get install -qq --no-install-recommends automake autoconf libbluetooth-dev libglib2.0-dev libtool libstartup-notification0-dev python-gi-dev intltool python3-dev cython python3-dbus dh-autoreconf

        # Travis environment is poluated
        - unset PYTHON_CFLAGS

      script:
        - ./autogen.sh
        - make
        - make check

    - language: python
      python: "3.6"
      install:
        - python -m pip install flake8
      script:
        - python -m flake8

    - language: python
      python: "3.4"
      install:
        - python -m pip install flake8
      script:
        - python -m flake8

    - language: python
      python: "3.7-dev"
      install:
        - python -m pip install flake8
      script:
        - python -m flake8
