language: python

cache: pip

virtualenv:
  system_site_packages: true

python: "3.4"

before_install:
  - sudo add-apt-repository ppa:vidplace7/bluez5-backports -y
  - sudo apt-get update -qq
  - sudo apt-get install --no-install-recommends libbluetooth-dev
  - sudo apt-get install -qq --no-install-recommends automake autoconf libglib2.0-dev libtool libgtk-3-dev libstartup-notification0-dev python-gi-dev intltool python3-dev cython python3-dbus dh-autoreconf

  # Travis environment is poluated
  - unset PYTHON_CFLAGS

install:
  - python -m pip install flake8

script:
  - ./autogen.sh
  - make
  - make check
  - python -m flake8
