language: python

python:
  - "3.4"
  - "3.6"
  - "3.7-dev"

script:
  - ./autogen.sh
  - make
  - make check
  - ${PYTHON} -m flake8

env:
  - PYTHON=python3.4

install:
 - python -m pip install flake8

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq automake autoconf libglib2.0-dev libtool libgtk-3-dev libstartup-notification0-dev python-gi-dev libbluetooth-dev intltool python3-dev cython python3-dbus dh-autoreconf
